export const siteConfig = {
  name: "Farrukh Sultan",
  title: "Farrukh Sultan | Senior Shopify Plus Developer & Full Stack Engineer",
  description:
    "Senior Shopify Plus Developer and Full Stack Engineer with 8+ years of experience building custom Shopify apps, checkout extensions, high-performance storefronts, headless commerce and AI-powered ecommerce products.",
  url: (process.env.NEXT_PUBLIC_SITE_URL || "https://farrukhsultan.dev").replace(/\/$/, ""),
  email: "farukh.5937@gmail.com",
  location: "Lahore, Pakistan",
  linkedin: "https://www.linkedin.com/in/farrukh-sultan-339721ba/",
  github: "https://github.com/AyFarukh",
  keywords: [
    "Farrukh Sultan",
    "Farrukh Sultan Shopify Developer",
    "Senior Shopify Developer",
    "Shopify Plus Developer",
    "Shopify Plus Expert",
    "Shopify App Developer",
    "Shopify Developer Pakistan",
    "Shopify Developer Lahore",
    "Shopify Checkout Developer",
    "Shopify Checkout UI Extensions",
    "Shopify Functions Developer",
    "Shopify Cart Transform API",
    "Shopify Liquid Developer",
    "Shopify OS 2.0 Developer",
    "Shopify Performance Optimization",
    "Headless Shopify Developer",
    "Headless Commerce Developer",
    "Hydrogen Developer",
    "Full Stack Developer",
    "Full Stack Engineer",
    "Next.js Developer",
    "React Developer",
    "TypeScript Developer",
    "Node.js Developer",
    "NestJS Developer",
    "GraphQL Developer",
    "AI Ecommerce Developer",
    "Computer Vision Developer",
  ],
};
